
-- Run this in your Supabase SQL Editor to set up the database

create table if not exists stations (
  id bigint primary key, -- respecting the manual ID setting from the frontend
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists routes (
  id bigint generated by default as identity primary key,
  source bigint references stations(id),
  destination bigint references stations(id),
  weight integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists vehicles (
  id bigint primary key,
  type text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists passengers (
  id bigint generated by default as identity primary key,
  name text,
  status text default 'waiting', -- waiting, processed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table stations enable row level security;
alter table routes enable row level security;
alter table vehicles enable row level security;
alter table passengers enable row level security;

-- Create policies (Allow all for demo purposes, adjust for production)
create policy "Public stations are viewable by everyone" on stations for select using (true);
create policy "Authenticated users can insert stations" on stations for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update stations" on stations for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete stations" on stations for delete using (auth.role() = 'authenticated');

create policy "Public routes are viewable by everyone" on routes for select using (true);
create policy "Authenticated users can insert routes" on routes for insert with check (auth.role() = 'authenticated');

create policy "Public vehicles are viewable by everyone" on vehicles for select using (true);
create policy "Authenticated users can insert vehicles" on vehicles for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can delete vehicles" on vehicles for delete using (auth.role() = 'authenticated');

create policy "Public passengers are viewable by everyone" on passengers for select using (true);
create policy "Authenticated users can insert passengers" on passengers for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update passengers" on passengers for update using (auth.role() = 'authenticated');
